version: '3'
services:
  lb:
    image: nginx
    ports:
      - "8080:80"
    depends_on:
      - web
      - web_two
      - web_three
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  db:
    image: postgres:9.6
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "todo_development"
      DEBUG: "true"

  chat-server:
    build:
      context: ./chat-app
    ports:
      - "5000:5000"

  web:
    build:
      context: ./todo
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - chat-server
    environment:
      RACK_ENV: "development"
      RAILS_ENV: "development"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "password"
      DEBUG: "true"

  web_two:
    build:
      context: ./todo
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3001:3000"
    depends_on:
      - db
      - chat-server
    environment:
      RACK_ENV: "development"
      RAILS_ENV: "development"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "password"
      DEBUG: "true"

  web_three:
    build:
      context: ./todo
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3002:3000"
    depends_on:
      - db
      - chat-server
    environment:
      RACK_ENV: "development"
      RAILS_ENV: "development"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "password"
      DEBUG: "true"

